name: Build NetStreamTV Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Java JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: 33.0.0
    
    - name: Install Node.js dependencies
      run: npm install
    
    - name: Make gradlew executable
      run: chmod +x android/gradlew
    
    - name: Clean project
      run: |
        cd android
        ./gradlew clean
    
    - name: Build Debug APK
      run: |
        cd android
        ./gradlew assembleDebug --stacktrace
    
    - name: Build Release APK
      run: |
        cd android
        ./gradlew assembleRelease --stacktrace
      continue-on-error: true
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: NetStreamTV-Debug-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
    
    - name: Upload Release APK (if available)
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: NetStreamTV-Release-APK
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 30
      continue-on-error: true
    
    - name: Create Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: NetStreamTV v1.0.${{ github.run_number }}
        body: |
          🎬 NetStreamTV Android TV App
          
          ✅ Netflix-style interface for Android TV
          ✅ IPTV live channels with EPG
          ✅ Remote control navigation
          ✅ Screen adaptation modes
          ✅ Professional video player
          
          📱 Install: Download APK and sideload to Android TV
        draft: false
        prerelease: false